"""Add document_location to deals

Revision ID: 0c5cf19635ec
Revises: 3f9bfda0ed64
Create Date: 2025-01-16 01:28:53.632881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0c5cf19635ec'
down_revision: Union[str, None] = '3f9bfda0ed64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_theses_id', table_name='theses')
    op.drop_table('theses')
    op.drop_table('key_statistics')
    op.drop_index('ix_thesis_surveys_id', table_name='thesis_surveys')
    op.drop_table('thesis_surveys')
    op.add_column('deals', sa.Column('document_location', sa.Text(), nullable=True))
    op.alter_column('rag_sessions', 'session_id',
               existing_type=mysql.CHAR(length=36),
               type_=sqlalchemy_utils.types.uuid.UUIDType(binary=False),
               existing_nullable=False)
    op.alter_column('rag_sessions', 'user_id',
               existing_type=mysql.CHAR(length=36),
               type_=sqlalchemy_utils.types.uuid.UUIDType(binary=False),
               existing_nullable=False)
    op.drop_constraint('rag_sessions_ibfk_1', 'rag_sessions', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('rag_sessions_ibfk_1', 'rag_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('rag_sessions', 'user_id',
               existing_type=sqlalchemy_utils.types.uuid.UUIDType(binary=False),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('rag_sessions', 'session_id',
               existing_type=sqlalchemy_utils.types.uuid.UUIDType(binary=False),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.drop_column('deals', 'document_location')
    op.create_table('thesis_surveys',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('thesis_title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('question', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('response', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('industry_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('industry_code', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('thesis_industry', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('thesis_expertise', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('thesis_characteristics', mysql.TEXT(), nullable=False),
    sa.Column('thesis_trends', mysql.TEXT(), nullable=False),
    sa.Column('thesis_growth', mysql.TEXT(), nullable=False),
    sa.Column('thesis_considerations', mysql.TEXT(), nullable=False),
    sa.Column('thesis_industry_recommendations', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_thesis_surveys_id', 'thesis_surveys', ['id'], unique=False)
    op.create_table('key_statistics',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('report_title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('report_date', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('metric', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('value', mysql.FLOAT(), nullable=True),
    sa.Column('historical_begin_year', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('historical_end_year', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('historical_cagr', mysql.FLOAT(), nullable=True),
    sa.Column('projected_begin_year', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('projected_end_year', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('projected_cagr', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('theses',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_theses_id', 'theses', ['id'], unique=False)
    # ### end Alembic commands ###
