"""Add Refresh token in user table

Revision ID: 1dc05da4fadf
Revises: 88ead811958d
Create Date: 2024-10-01 18:26:20.767237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dc05da4fadf'
down_revision: Union[str, None] = '88ead811958d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('calendly_refresh_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'calendly_refresh_token')
    # ### end Alembic commands ###
