"""Updated project, documents columns types with relationships

Revision ID: 286cbd70c398
Revises: d59e0dade6f9
Create Date: 2025-03-26 18:21:37.763523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '286cbd70c398'
down_revision: Union[str, None] = 'd59e0dade6f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
