"""Updated users table

Revision ID: 3b3f0651ccea
Revises: 33c90d44da63
Create Date: 2024-10-04 12:01:15.598827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b3f0651ccea'
down_revision: Union[str, None] = '33c90d44da63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_master_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_master_admin')
    # ### end Alembic commands ###
