"""Added type in chatsession

Revision ID: 46e8e130a94a
Revises: 679dfa3c4de2
Create Date: 2024-10-14 14:21:48.572797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46e8e130a94a'
down_revision: Union[str, None] = '679dfa3c4de2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'type')
    # ### end Alembic commands ###
