"""Modified the priority schema

Revision ID: 5fae3170bb69
Revises: a45c31ddd5bb
Create Date: 2024-09-24 18:51:40.862176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5fae3170bb69'
down_revision: Union[str, None] = 'a45c31ddd5bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'priority',
               existing_type=mysql.ENUM('high', 'medium', 'low'),
               type_=sa.String(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'priority',
               existing_type=sa.String(length=255),
               type_=mysql.ENUM('high', 'medium', 'low'),
               nullable=False)
    # ### end Alembic commands ###
