"""modified users schema

Revision ID: 5fb7feba0299
Revises: 3b3f0651ccea
Create Date: 2024-10-04 15:06:11.598640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fb7feba0299'
down_revision: Union[str, None] = '3b3f0651ccea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('user_id', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'chat_sessions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_column('chat_sessions', 'user_id')
    # ### end Alembic commands ###
