"""Add like_dislike_status to chat_messages

Revision ID: 60fa3b0f624b
Revises: 6bcf64f74b96
Create Date: 2024-10-08 17:33:16.476050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60fa3b0f624b'
down_revision: Union[str, None] = '6bcf64f74b96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('like_dislike_status', sa.Enum('NONE', 'LIKE', 'DISLIKE', name='likedislikestatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'like_dislike_status')
    # ### end Alembic commands ###
