"""Added updated at in deals

Revision ID: 679dfa3c4de2
Revises: 60fa3b0f624b
Create Date: 2024-10-14 11:35:40.503337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '679dfa3c4de2'
down_revision: Union[str, None] = '60fa3b0f624b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deals', 'updated_at')
    # ### end Alembic commands ###
