"""Add created_at to chat_sessions

Revision ID: 6bcf64f74b96
Revises: f2e8430e2403
Create Date: 2024-10-08 14:07:41.086839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bcf64f74b96'
down_revision: Union[str, None] = 'f2e8430e2403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'created_at')
    # ### end Alembic commands ###
