"""Updated users table

Revision ID: 88ead811958d
Revises: 07b7e0c58317
Create Date: 2024-10-01 17:55:48.177389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88ead811958d'
down_revision: Union[str, None] = '07b7e0c58317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('calendly_access_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'calendly_access_token')
    # ### end Alembic commands ###
