"""Modified the task schema

Revision ID: a45c31ddd5bb
Revises: b393371e20d1
Create Date: 2024-09-24 18:36:31.378478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a45c31ddd5bb'
down_revision: Union[str, None] = 'b393371e20d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('due_date', sa.TIMESTAMP(), nullable=True))
    op.add_column('todos', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('todos', sa.Column('priority', sa.Enum('high', 'medium', 'low', name='prioritylevel'), nullable=False))
    op.add_column('todos', sa.Column('custom_tags', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'custom_tags')
    op.drop_column('todos', 'priority')
    op.drop_column('todos', 'description')
    op.drop_column('todos', 'due_date')
    # ### end Alembic commands ###
