"""added_roles_in_deals

Revision ID: c6e85fed5672
Revises: d0aa4bb0a3bf
Create Date: 2024-10-03 18:21:22.906210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6e85fed5672'
down_revision: Union[str, None] = 'd0aa4bb0a3bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('role', sa.Enum('DOCUMENT_COLLABORATOR', 'FULL_COLLABORATOR', name='userrole'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deals', 'role')
    # ### end Alembic commands ###
