"""added_roles

Revision ID: d0aa4bb0a3bf
Revises: 33c90d44da63
Create Date: 2024-10-03 18:07:01.594222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0aa4bb0a3bf'
down_revision: Union[str, None] = '33c90d44da63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newUsersDeals', sa.Column('role', sa.Enum('DOCUMENT_COLLABORATOR', 'FULL_COLLABORATOR', name='userrole'), nullable=False))
    op.add_column('sharedUserDeals', sa.Column('role', sa.Enum('DOCUMENT_COLLABORATOR', 'FULL_COLLABORATOR', name='userrole'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sharedUserDeals', 'role')
    op.drop_column('newUsersDeals', 'role')
    # ### end Alembic commands ###
