"""Initial migration for Project, Document, and Report

Revision ID: d23e8258ddc0
Revises: 0c5cf19635ec
Create Date: 2025-03-26 16:23:43.207360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision: str = 'd23e8258ddc0'
down_revision: Union[str, None] = '0c5cf19635ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_us')
    op.drop_table('reports')
    op.alter_column('rag_sessions', 'user_id',
               existing_type=mysql.CHAR(length=36),
               type_=sqlalchemy_utils.types.uuid.UUIDType(binary=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rag_sessions', 'user_id',
               existing_type=sqlalchemy_utils.types.uuid.UUIDType(binary=False),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.create_table('reports',
    sa.Column('id', mysql.CHAR(length=32), nullable=False),
    sa.Column('deal_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('report_data', mysql.LONGTEXT(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('contact_us',
    sa.Column('id', mysql.CHAR(length=36), server_default=sa.text('(uuid())'), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
