"""Added research field to ReportTable

Revision ID: ff6a2537222e
Revises: a0d420904fbe
Create Date: 2025-04-02 19:45:09.505987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ff6a2537222e'
down_revision: Union[str, None] = 'a0d420904fbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('summaries')
    op.drop_index('meeting_id', table_name='transcriptions')
    op.drop_table('transcriptions')
    op.add_column('reports_table', sa.Column('sections', sa.JSON(), nullable=True))
    op.add_column('reports_table', sa.Column('research', sa.Enum('deep', 'research', name='research_type'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports_table', 'research')
    op.drop_column('reports_table', 'sections')
    op.create_table('transcriptions',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('meeting_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('transcript', mysql.TEXT(), nullable=False),
    sa.Column('recording_date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('duration', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('participants', mysql.JSON(), nullable=True),
    sa.Column('meeting_metadata', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('meeting_id', 'transcriptions', ['meeting_id'], unique=True)
    op.create_table('summaries',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('transcription_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('meeting_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('summary_data', mysql.JSON(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['transcription_id'], ['transcriptions.id'], name='summaries_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
