services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8002:8080"
    depends_on:
      - ollama
    environment:
      QUERY_DEFAULTS_LIMIT: 100
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "./database"
      ENABLE_MODULES: "text2vec-ollama"
      OLLAMA_BASE_URL: "http://ollama:8001"

  ollama:
    image: ollama/ollama:latest
    ports:
      - "8001:8000"

  app:
    build: .
    depends_on:
      - weaviate
      - ollama
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_MODEL_NAME="your_model_name"
