services:

  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8002:8080"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: ${QUERY_DEFAULTS_LIMIT}
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: ${AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED}
      PERSISTENCE_DATA_PATH: ${PERSISTENCE_DATA_PATH}
      ENABLE_MODULES: ${ENABLE_MODULES}
      OPENAI_APIKEY: ${OPENAI_API_KEY}

  llmsherpa:
    image: ghcr.io/nlmatics/nlm-ingestor:latest
    ports:
      - "5501:5001"

  app:
    build: .
    depends_on:
      - weaviate
    ports:
      - "8004:8000"
      - "8003:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_MODEL_NAME=${OPENAI_MODEL_NAME}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BING_API_KEY=${BING_API_KEY}
      - FMP_API_KEY=${FMP_API_KEY}
      - POLYGON_API_KEY=${POLYGON_API_KEY}
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
      - TIINGO_API_KEY=${TIINGO_API_KEY}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # volumes:
    #   - ./frontend:/app
      # - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: ["npm", "start"]
