version: '3.8'

services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8002:8080"
    depends_on:
      - ollama
    environment:
      QUERY_DEFAULTS_LIMIT: ${QUERY_DEFAULTS_LIMIT}
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: ${AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED}
      PERSISTENCE_DATA_PATH: ${PERSISTENCE_DATA_PATH}
      ENABLE_MODULES: ${ENABLE_MODULES}
      OPENAI_APIKEY: ${OPENAI_API_KEY}

  ollama:
    image: ollama/ollama:latest
    ports:
      - "8001:11434"

  app:
    build: .
    depends_on:
      - weaviate
      - ollama
    ports:
      - "8004:8000"
      - "8003:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_MODEL_NAME=${OPENAI_MODEL_NAME}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BING_API_KEY=${BING_API_KEY}
