services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_MODEL_NAME=${OPENAI_MODEL_NAME}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BING_API_KEY=${BING_API_KEY}
      - FMP_API_KEY=${FMP_API_KEY}
      - POLYGON_API_KEY=${POLYGON_API_KEY}
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
      - TIINGO_API_KEY=${TIINGO_API_KEY}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER_NAME=${DATABASE_USER_NAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - CALENDLY_CLIENT_ID=${CALENDLY_CLIENT_ID}
      - CALENDLY_CLIENT_SECRET=${CALENDLY_CLIENT_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}
      - WEAVIATE_HOST=${WEAVIATE_HOST}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    command: >
      /bin/sh -c "alembic upgrade head && uvicorn app:app --host 0.0.0.0 --port 8000 --reload --loop asyncio"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    command: ["npm", "run", "dev"]

  scraper:
    build:
      context: ./Omega_scraper
      dockerfile: ./Dockerfile
    ports:
      - 8008:8008
    volumes:
      - .:/Omega_scraper
    environment:
      - PYTHONUNBUFFERED=1
      - FIRECRAWL_API_KEY=fc-03c54bbfef47490ab832485ecb1bf21c
    command:
      # fastapi run --reload --port 8008 app.py   # for dev, with reload
      fastapi run --workers 8 --port 8008 app.py # for PROD, no reloads, several workers

