services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./logs:/app/logs 
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_MODEL_NAME=${OPENAI_MODEL_NAME}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BING_API_KEY=${BING_API_KEY}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER_NAME=${DATABASE_USER_NAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=omni_ai_testdb
      - DATABASE_PORT=${DATABASE_PORT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    command: ["npm", "run", "dev"]