services:

  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8401:8401"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DOCKER_BUILDKIT=${DOCKER_BUILDKIT}
    command:
      fastapi run --workers 16 --port 8401 app.py
