services:

  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8008:8008
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - FIRECRAWL_API_KEY=fc-03c54bbfef47490ab832485ecb1bf21c
    command:
      # uvicorn app:app --host 0.0.0.0 --port 8401 --reload
      fastapi run --workers 4 --port 8008 app.py
