name: CI

on:
  pull_request:
    branches:
      - development

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Set up Docker Compose
      run: sudo apt-get install docker-compose

    - name: Build and run Weaviate services
      run: docker-compose -f docker-compose-weaviate.yaml up --build -d

    - name: Build and run application services
      run: docker-compose -f docker-compose-application.yaml up --build -d

    - name: Wait for services to be healthy
      run: |
        while ! curl -sSf http://localhost:8000/health; do
          echo "Waiting for backend to be healthy..."
          sleep 5
        done
        while ! curl -sSf http://localhost:3000; do
          echo "Waiting for frontend to be healthy..."
          sleep 5
        done

    - name: Run backend tests
      run: docker-compose -f docker-compose-application.yaml exec app pytest api/api/tests/dummy_test.py

    - name: Run frontend tests
      run: docker-compose -f docker-compose-application.yaml exec frontend npm test frontend/tests/dummy_test.js